[window]
opacity = 0.8
dynamic_padding = true
decorations="None"
startup_mode="Maximized"

#[terminal.shell]
#program = "/usr/bin/byobu"
#args = [ "-S", ".local/state/byobu-session" ]

[font.offset]
x = 0
y = 0

[window.dimensions]
columns = 120
lines = 35

[window.padding]
x = 0
y = 0
